version: '3'
services:
  php:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
